language: csharp
solution: TodoApi.sln

matrix:
  include:
    - dotnet: 2.1.4
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest